twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    paths:
        'assets/static': static
        'assets/css': css
        'assets/scss': scss
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'forms/materialize-layout.html.twig'