easy_admin:
    entities:
        User:
            class: App\Entity\User
            label: 'User'
            list:
                fields:
                    - firstname
                    - lastname
                    - email
            form:
                fields:
                    - firstname
                    - lastname
                    - email
                    - adminEmailReceiver
                    - property: 'role'
                      type: 'choice'
                      type_options:
                          mapped: true
                          expanded: false
                          multiple: false
                          required: true
                          choices:
                              'User': !php/const App\Entity\User::ROLE_USER
                              'Admin': !php/const App\Entity\User::ROLE_ADMIN
                              'Super Admin': !php/const App\Entity\User::ROLE_SUPER_ADMIN
            show:
                fields:
                    - username
                    - email
